variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

nightly:cargo:
  image: rustdocker/rust:nightly
  stage: test
  coverage: '/^\d+.\d+% coverage/'
  script:
    - rustup default nightly-2022-08-14
    - rustup target add wasm32-unknown-unknown
    # - cargo install trunk --locked
    # - (cd client; trunk build)
    - cargo install cargo-tarpaulin -f
    - cargo test --manifest-path client/Cargo.toml --verbose --jobs 1
    - cargo test --manifest-path common/Cargo.toml --verbose --jobs 1
    # - cargo test --manifest-path server/Cargo.toml --verbose --jobs 1
    - cargo tarpaulin --manifest-path common/Cargo.toml --out Xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  cache:
    key: shared-cache
    paths:
      - target/
      - .cargo/